config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/welcome", to: "welcome#index"

  post "/users/logout", to: "users#logout"

  get "/users/login", to: "users#login"
  post "/users/login", to: "users#user_login"

  root 'articles#index'
  get "articles/random", to: "articles#random"

  #post "comments/upvote/:user_id/:comment", to: "comments#upvote"
  post "articles/:article_id/comments/:id/upvote", to: "comments#upvote"
  post "articles/:article_id/comments/:id/downvote", to: "comments#downvote"



  resources :users
  resources :articles do
    resources :comments
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  include Visible
  belongs_to :user, foreign_key: "author_id"

  has_many :comments, dependent: :delete_all

  validates :title, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  def avg_rating
    comments.average(:rating).to_i
  end

  def self.random
    # return a random article
    Article.all.sample
  end


end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
  belongs_to :user

  validates :body, presence: true

  def upvoter(user_id)
    upvotes = self.upvote
    downvotes = self.downvote
    if downvotes.include?(user_id)
      downvotes.delete(user_id)
      upvotes.push(user_id)
    elsif upvotes.include?(user_id)
      upvotes.delete(user_id)
    else
      upvotes.push(user_id)
    end
    self.save
  end

  def downvoter(user_id)
    upvotes = self.upvote
    downvotes = self.downvote
    if upvotes.include?(user_id)
      upvotes.delete(user_id)
      downvotes.push(user_id)
    elsif downvotes.include?(user_id)
      downvotes.delete(user_id)
    else
      downvotes.push(user_id)
    end
    self.save
  end


end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern

  VALID_STATUSES = ['public', 'private', 'archived']

  included do
    validates :status, inclusion: { in: VALID_STATUSES }
  end

  class_methods do
    def public_count
      where(status: 'public').count
    end
  end

  def archived?
    status == 'archived'
  end
end

app/models/user.rb
class User < ApplicationRecord
  include Visible

  has_many :articles, dependent: :delete_all
  has_many :comments, dependent: :delete_all

  validates :username, presence:true, uniqueness:true
  validates :password, presence:true



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
    @user = User.find(session[:current_user_id]) unless session[:current_user_id].nil?
  end

  def new
    @article = Article.new
  end

  def create
    @user = User.find(session[:current_user_id])
    @article = Article.new(article_params.merge(author_id: @user.id))

    if @article.save
      redirect_to @article
    else
      render :new
    end 
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to root_path
  end

  def random
    redirect_to Article.random
  end

  private
  def article_params
    params.require(:article).permit(:title, :body)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @user = User.find(session[:current_user_id])
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params.merge(commenter: @user.username, article_id: params[:article_id], user_id: session[:current_user_id]))
    redirect_to article_path(@article)
  end

  def destroy
    @user = User.find(session[:current_user_id])
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
    redirect_to article_path(@article)
  end 

  def upvote
    user_id = User.find(session[:current_user_id]).id
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.upvoter(user_id)

    redirect_to article_path(@article)
  end

  def downvote
    user_id = User.find(session[:current_user_id]).id
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.downvoter(user_id)

    redirect_to article_path(@article)
  end




  private
  def comment_params
    params.require(:comment).permit(:body, :rating)
  end
end

app/controllers/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern
  class_methods do
    def public_count
      Article.count
    end

    def logged_in?(user_id)
      where(id: user_id).exists?
    end

    def author?(current_user_id, author_id)
      current_user_id == author_id
    end

    def random_article_id
      arr = Article.all.each.with_object([]) { |a, array| array.push(a.id) }
      arr.sample
    end

    def upvote(user_id, comment)
      comment.upvote.push(user_id)
      comment.save
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    session[:current_user_id] = @user.id
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def login
    @user = User.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:current_user_id] = @user.id
      session[:current_user_username] = @user.username
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
    @user = User.find(session[:current_user_id])
  end

  def update
    @user = User.find(session[:current_user_id])

    if @user.update(user_params)
      session[:current_user_username] = @user.username
      redirect_to root_url
    else
      redirect_to edit_user_url
    end
  end

  def logout
    reset_session
    redirect_to root_url
  end

  def user_login
    @user = User.find_by(user_params)
    if !@user.nil?
      session[:current_user_id] = @user.id
      session[:current_user_username] = @user.username
      redirect_to root_url
    else
      redirect_to new_user_url
    end
  end

  def destroy
    #@user = User.find(session[:current_user_id])
    Article.where(author_id: session[:current_user_id]).destroy_all
    Comment.where(user_id: session[:current_user_id]).destroy_all
    #User.where(id: session[:current_user_id]).destroy_all
    #@user.destroy
    User.delete(session[:current_user_id])
    redirect_to root_url
  end

  private
  def user_params
    params.require(:user).permit(:username,:password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_with model: @article do |form| %>

  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%= link_to "Home", "/articles" %>

<h1>Edit Article</h1>

<% if User.logged_in?(session[:current_user_id]) && User.author?(session[:current_user_id], @article.author_id)%>
  <%= render "form", article: @article %>
<% end %>

app/views/articles/index.html.erb
<%#= stylesheet_link_tag 'application', 'assets/stylesheets/' %>
<% if User.logged_in?(session[:current_user_id]) %>
  <p>welcome <%= session[:current_user_username] %>!</p>
  <%= link_to "Edit Account", edit_user_path(session[:current_user_id]) %>
  <%= link_to "Delete Account", user_path(session[:current_user_username]),  data: { confirm: "are you sure you want to delete your account: #{session[:current_user_username]} and all it's content?" }, method: :delete %>
  <%= form_tag "/users/logout" do %>
    <%= submit_tag 'logout' %>
  <% end %>

<% else %>
  <%= link_to "Register Account", new_user_path %>
  <%= link_to "login", "/users/login" %>

<% end %>

</div>
<h1>Articles</h1>
<p>our blog has <%= Article.public_count %> <%= Article.public_count == 1 ? 'article' : 'articles' %> and counting!</p>

<table>
  <tr>
    <th>Article</th>
    <th>Author</th>
    <th>Last Update</th>
    <th>Rating</th>
  </tr>
  <% @articles.each do |article| %>
    <tr>
      <td>
        <%= link_to article.title, article %> 
      </td>
      <td>
        <%= article.user.username %>
      </td>
      <td>
        <%= article.updated_at.strftime('%F') %>
      </td>
      <td><span>
          <% article.avg_rating.times do %>
            <%= image_tag 'star.svg.png' %>
          <% end %>
          <% if article.avg_rating == 0 %>
          No rating
          <% end %>
        </span>
      </td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to "random article", "articles/random" %>
</p>

<% if User.logged_in?(session[:current_user_id]) %>
  <%= link_to "New Article", new_article_path %>
<% else %>
  <p>You must be logged in to create articles</p>
<% end %>

app/views/articles/new.html.erb
<%= link_to "Home", "/articles" %>

<h1>New Article</h1>

<% if User.logged_in?(session[:current_user_id]) %>
  <%= render "form", article: @article %>
<% end %>

app/views/articles/show.html.erb
<%= link_to "Home", "/articles" %>

<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
  <% if User.logged_in?(session[:current_user_id]) && User.author?(session[:current_user_id], @article.author_id) %>
    <li><%= link_to "Edit", edit_article_path(@article)  %></li>
    <li><%= link_to "Destroy", article_path(@article),
      method: :delete,
      data: { confirm: "Are you sure you want to delete #{@article.title}?" } %></li>
  <% end %>
</ul>

<h2>Comments</h2>
<%= render @article.comments %>

<% if User.logged_in?(session[:current_user_id]) %>
  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>
<% else %>
  <p>You must be logged in to comment</p>
  <%= link_to "Register Account", new_user_path %>
  <%= link_to "login", "/users/login" %>
<% end %>

app/views/comments/_comment.html.erb
<p>
  <strong>Rating:</strong>
  <% comment.rating.times do %>
    <%= image_tag 'star.svg.png' %>
  <% end %>
</p>

<p>
  <strong>Commenter:</strong>
  <%= comment.user.username %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<% if User.logged_in?(session[:current_user_id]) && User.author?(session[:current_user_id], comment.user_id) %>
  <span>
    <%= form_tag article_comment_path(@article.id, comment) << "/upvote" do %>
      <%= image_submit_tag('up_arrow.png') %>
    <% end %>
    <%= comment.upvote.size - comment.downvote.size %>

    <%= form_tag article_comment_path(@article.id, comment) << "/downvote" do %>
      <%= image_submit_tag('down_arrow.png') %>
    <% end %> 
  </span>


  <p>
  <%= link_to "Destroy Comment", [comment.article, comment],
    method: :delete,
    data: { confirm: "are you sure you want to delete #{comment.body}" } %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<% if User.logged_in?(session[:current_user_id]) %>
  <%= form_with model: [ @article, @article.comments.build ] do |form| %>
    <p>
      <%= form.label :rating %><br>
      <%= form.select :rating, [1,2,3,4,5], selected: 5 %>
    </p>


    <p>
      <%= form.label :body %><br>
      <%= form.text_area :body %>
    </p>

    <p>
      <%= form.submit %>
    </p>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('prayer.png') %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :username %><br>
    <%= form.text_field :username %>
    <% @user.errors.full_messages_for(:username).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :password %><br>
    <%= form.text_area :password %>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
 </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<%= link_to "Home", "/articles" %>

<h1>Edit Username/Password</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

app/views/users/login.html.erb
<%= link_to "Home", "/articles" %>

<h1>login</h1>

<%= form_for @user, :url => { :action => "user_login" } do |form| %>
  <div>
    <%= form.label :username %><br>
    <%= form.text_field :username %>
    <% @user.errors.full_messages_for(:username).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :password %><br>
    <%= form.text_area :password %>
    <% @user.errors.full_messages_for(:password).each do |message| %>
      <div><%= message %></div>
    <% end %>
 </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New Account</h1>

<% puts @user.inspect %>

<%= render "form", user: @user %>

app/views/welcome/index.html.erb
<h2>Hello world</h2>
<p>
  the time now is: <%= Time.now %>
</p>